package com.gplucky.common.mybatis.model;

import java.util.Date;

public class StockParams {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_params.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_params.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_params.up_days
     *
     * @mbggenerated
     */
    private Integer upDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_params.down_days
     *
     * @mbggenerated
     */
    private Integer downDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_params.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_params.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_params.id
     *
     * @return the value of stock_params.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_params.id
     *
     * @param id the value for stock_params.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_params.symbol
     *
     * @return the value of stock_params.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_params.symbol
     *
     * @param symbol the value for stock_params.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_params.up_days
     *
     * @return the value of stock_params.up_days
     *
     * @mbggenerated
     */
    public Integer getUpDays() {
        return upDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_params.up_days
     *
     * @param upDays the value for stock_params.up_days
     *
     * @mbggenerated
     */
    public void setUpDays(Integer upDays) {
        this.upDays = upDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_params.down_days
     *
     * @return the value of stock_params.down_days
     *
     * @mbggenerated
     */
    public Integer getDownDays() {
        return downDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_params.down_days
     *
     * @param downDays the value for stock_params.down_days
     *
     * @mbggenerated
     */
    public void setDownDays(Integer downDays) {
        this.downDays = downDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_params.create_time
     *
     * @return the value of stock_params.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_params.create_time
     *
     * @param createTime the value for stock_params.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_params.update_time
     *
     * @return the value of stock_params.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_params.update_time
     *
     * @param updateTime the value for stock_params.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}