package com.gplucky.common.mybatis.model;

import java.util.Date;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.trade
     *
     * @mbggenerated
     */
    private String trade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.pricechange
     *
     * @mbggenerated
     */
    private String pricechange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.changepercent
     *
     * @mbggenerated
     */
    private String changepercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.buy
     *
     * @mbggenerated
     */
    private String buy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.sell
     *
     * @mbggenerated
     */
    private String sell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.settlement
     *
     * @mbggenerated
     */
    private String settlement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.open
     *
     * @mbggenerated
     */
    private String open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.high
     *
     * @mbggenerated
     */
    private String high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.low
     *
     * @mbggenerated
     */
    private String low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.volume
     *
     * @mbggenerated
     */
    private Integer volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.ticktime
     *
     * @mbggenerated
     */
    private String ticktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.code
     *
     * @return the value of stock.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.code
     *
     * @param code the value for stock.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.symbol
     *
     * @return the value of stock.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.symbol
     *
     * @param symbol the value for stock.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.name
     *
     * @return the value of stock.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.name
     *
     * @param name the value for stock.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.score
     *
     * @return the value of stock.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.score
     *
     * @param score the value for stock.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.trade
     *
     * @return the value of stock.trade
     *
     * @mbggenerated
     */
    public String getTrade() {
        return trade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.trade
     *
     * @param trade the value for stock.trade
     *
     * @mbggenerated
     */
    public void setTrade(String trade) {
        this.trade = trade == null ? null : trade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.pricechange
     *
     * @return the value of stock.pricechange
     *
     * @mbggenerated
     */
    public String getPricechange() {
        return pricechange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.pricechange
     *
     * @param pricechange the value for stock.pricechange
     *
     * @mbggenerated
     */
    public void setPricechange(String pricechange) {
        this.pricechange = pricechange == null ? null : pricechange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.changepercent
     *
     * @return the value of stock.changepercent
     *
     * @mbggenerated
     */
    public String getChangepercent() {
        return changepercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.changepercent
     *
     * @param changepercent the value for stock.changepercent
     *
     * @mbggenerated
     */
    public void setChangepercent(String changepercent) {
        this.changepercent = changepercent == null ? null : changepercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.buy
     *
     * @return the value of stock.buy
     *
     * @mbggenerated
     */
    public String getBuy() {
        return buy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.buy
     *
     * @param buy the value for stock.buy
     *
     * @mbggenerated
     */
    public void setBuy(String buy) {
        this.buy = buy == null ? null : buy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.sell
     *
     * @return the value of stock.sell
     *
     * @mbggenerated
     */
    public String getSell() {
        return sell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.sell
     *
     * @param sell the value for stock.sell
     *
     * @mbggenerated
     */
    public void setSell(String sell) {
        this.sell = sell == null ? null : sell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.settlement
     *
     * @return the value of stock.settlement
     *
     * @mbggenerated
     */
    public String getSettlement() {
        return settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.settlement
     *
     * @param settlement the value for stock.settlement
     *
     * @mbggenerated
     */
    public void setSettlement(String settlement) {
        this.settlement = settlement == null ? null : settlement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.open
     *
     * @return the value of stock.open
     *
     * @mbggenerated
     */
    public String getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.open
     *
     * @param open the value for stock.open
     *
     * @mbggenerated
     */
    public void setOpen(String open) {
        this.open = open == null ? null : open.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.high
     *
     * @return the value of stock.high
     *
     * @mbggenerated
     */
    public String getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.high
     *
     * @param high the value for stock.high
     *
     * @mbggenerated
     */
    public void setHigh(String high) {
        this.high = high == null ? null : high.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.low
     *
     * @return the value of stock.low
     *
     * @mbggenerated
     */
    public String getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.low
     *
     * @param low the value for stock.low
     *
     * @mbggenerated
     */
    public void setLow(String low) {
        this.low = low == null ? null : low.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.volume
     *
     * @return the value of stock.volume
     *
     * @mbggenerated
     */
    public Integer getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.volume
     *
     * @param volume the value for stock.volume
     *
     * @mbggenerated
     */
    public void setVolume(Integer volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.amount
     *
     * @return the value of stock.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.amount
     *
     * @param amount the value for stock.amount
     *
     * @mbggenerated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.ticktime
     *
     * @return the value of stock.ticktime
     *
     * @mbggenerated
     */
    public String getTicktime() {
        return ticktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.ticktime
     *
     * @param ticktime the value for stock.ticktime
     *
     * @mbggenerated
     */
    public void setTicktime(String ticktime) {
        this.ticktime = ticktime == null ? null : ticktime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.create_time
     *
     * @return the value of stock.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.create_time
     *
     * @param createTime the value for stock.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.update_time
     *
     * @return the value of stock.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.update_time
     *
     * @param updateTime the value for stock.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}