package com.gplucky.common.mybatis.model;

import java.util.Date;

public class StockNew {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.trade
     *
     * @mbggenerated
     */
    private String trade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.pricechange
     *
     * @mbggenerated
     */
    private String pricechange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.changepercent
     *
     * @mbggenerated
     */
    private String changepercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.buy
     *
     * @mbggenerated
     */
    private String buy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.sell
     *
     * @mbggenerated
     */
    private String sell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.settlement
     *
     * @mbggenerated
     */
    private String settlement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.open
     *
     * @mbggenerated
     */
    private String open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.high
     *
     * @mbggenerated
     */
    private String high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.low
     *
     * @mbggenerated
     */
    private String low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.volume
     *
     * @mbggenerated
     */
    private Long volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.amount
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.ticktime
     *
     * @mbggenerated
     */
    private String ticktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_new.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.id
     *
     * @return the value of stock_new.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.id
     *
     * @param id the value for stock_new.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.code
     *
     * @return the value of stock_new.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.code
     *
     * @param code the value for stock_new.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.symbol
     *
     * @return the value of stock_new.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.symbol
     *
     * @param symbol the value for stock_new.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.name
     *
     * @return the value of stock_new.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.name
     *
     * @param name the value for stock_new.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.score
     *
     * @return the value of stock_new.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.score
     *
     * @param score the value for stock_new.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.trade
     *
     * @return the value of stock_new.trade
     *
     * @mbggenerated
     */
    public String getTrade() {
        return trade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.trade
     *
     * @param trade the value for stock_new.trade
     *
     * @mbggenerated
     */
    public void setTrade(String trade) {
        this.trade = trade == null ? null : trade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.pricechange
     *
     * @return the value of stock_new.pricechange
     *
     * @mbggenerated
     */
    public String getPricechange() {
        return pricechange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.pricechange
     *
     * @param pricechange the value for stock_new.pricechange
     *
     * @mbggenerated
     */
    public void setPricechange(String pricechange) {
        this.pricechange = pricechange == null ? null : pricechange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.changepercent
     *
     * @return the value of stock_new.changepercent
     *
     * @mbggenerated
     */
    public String getChangepercent() {
        return changepercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.changepercent
     *
     * @param changepercent the value for stock_new.changepercent
     *
     * @mbggenerated
     */
    public void setChangepercent(String changepercent) {
        this.changepercent = changepercent == null ? null : changepercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.buy
     *
     * @return the value of stock_new.buy
     *
     * @mbggenerated
     */
    public String getBuy() {
        return buy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.buy
     *
     * @param buy the value for stock_new.buy
     *
     * @mbggenerated
     */
    public void setBuy(String buy) {
        this.buy = buy == null ? null : buy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.sell
     *
     * @return the value of stock_new.sell
     *
     * @mbggenerated
     */
    public String getSell() {
        return sell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.sell
     *
     * @param sell the value for stock_new.sell
     *
     * @mbggenerated
     */
    public void setSell(String sell) {
        this.sell = sell == null ? null : sell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.settlement
     *
     * @return the value of stock_new.settlement
     *
     * @mbggenerated
     */
    public String getSettlement() {
        return settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.settlement
     *
     * @param settlement the value for stock_new.settlement
     *
     * @mbggenerated
     */
    public void setSettlement(String settlement) {
        this.settlement = settlement == null ? null : settlement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.open
     *
     * @return the value of stock_new.open
     *
     * @mbggenerated
     */
    public String getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.open
     *
     * @param open the value for stock_new.open
     *
     * @mbggenerated
     */
    public void setOpen(String open) {
        this.open = open == null ? null : open.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.high
     *
     * @return the value of stock_new.high
     *
     * @mbggenerated
     */
    public String getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.high
     *
     * @param high the value for stock_new.high
     *
     * @mbggenerated
     */
    public void setHigh(String high) {
        this.high = high == null ? null : high.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.low
     *
     * @return the value of stock_new.low
     *
     * @mbggenerated
     */
    public String getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.low
     *
     * @param low the value for stock_new.low
     *
     * @mbggenerated
     */
    public void setLow(String low) {
        this.low = low == null ? null : low.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.volume
     *
     * @return the value of stock_new.volume
     *
     * @mbggenerated
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.volume
     *
     * @param volume the value for stock_new.volume
     *
     * @mbggenerated
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.amount
     *
     * @return the value of stock_new.amount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.amount
     *
     * @param amount the value for stock_new.amount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.ticktime
     *
     * @return the value of stock_new.ticktime
     *
     * @mbggenerated
     */
    public String getTicktime() {
        return ticktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.ticktime
     *
     * @param ticktime the value for stock_new.ticktime
     *
     * @mbggenerated
     */
    public void setTicktime(String ticktime) {
        this.ticktime = ticktime == null ? null : ticktime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.create_time
     *
     * @return the value of stock_new.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.create_time
     *
     * @param createTime the value for stock_new.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_new.update_time
     *
     * @return the value of stock_new.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_new.update_time
     *
     * @param updateTime the value for stock_new.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}