package com.gplucky.common.mybatis.dao;

import com.gplucky.common.mybatis.model.StockParams;
import com.gplucky.common.mybatis.model.StockParamsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_params
     *
     * @mbggenerated
     */
    int countByExample(StockParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_params
     *
     * @mbggenerated
     */
    int deleteByExample(StockParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_params
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_params
     *
     * @mbggenerated
     */
    int insert(StockParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_params
     *
     * @mbggenerated
     */
    int insertSelective(StockParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_params
     *
     * @mbggenerated
     */
    List<StockParams> selectByExample(StockParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_params
     *
     * @mbggenerated
     */
    StockParams selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_params
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockParams record, @Param("example") StockParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_params
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockParams record, @Param("example") StockParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_params
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StockParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_params
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StockParams record);
}