package com.gplucky.common.mybatis.dao;

import com.gplucky.common.mybatis.model.StockNew;
import com.gplucky.common.mybatis.model.StockNewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockNewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_new
     *
     * @mbggenerated
     */
    int countByExample(StockNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_new
     *
     * @mbggenerated
     */
    int deleteByExample(StockNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_new
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_new
     *
     * @mbggenerated
     */
    int insert(StockNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_new
     *
     * @mbggenerated
     */
    int insertSelective(StockNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_new
     *
     * @mbggenerated
     */
    List<StockNew> selectByExample(StockNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_new
     *
     * @mbggenerated
     */
    StockNew selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_new
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockNew record, @Param("example") StockNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_new
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockNew record, @Param("example") StockNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_new
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StockNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_new
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StockNew record);
}