package com.gplucky.common.mybatis.dao;

import com.gplucky.common.mybatis.model.TaskHistory;
import com.gplucky.common.mybatis.model.TaskHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbggenerated
     */
    int countByExample(TaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbggenerated
     */
    int deleteByExample(TaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbggenerated
     */
    int insert(TaskHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbggenerated
     */
    int insertSelective(TaskHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbggenerated
     */
    List<TaskHistory> selectByExample(TaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbggenerated
     */
    TaskHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TaskHistory record, @Param("example") TaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TaskHistory record, @Param("example") TaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskHistory record);
}